name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency: ci-${{ github.ref }}

jobs:
  checks:
    strategy:
      matrix:
        check:
          - lint:ci
          - prettier:ci
    name: ${{ matrix.check }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run ${{ matrix.check }}
        run: npm run ${{ matrix.check }}
